### PR TITLE
Adding demo dockerfile working with UbuntuGIS ppa

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
I will continue with integration of https://github.com/ZOO-Project/examples

**Comment by kalxas** [comment]
@gfenoy can you please review?

**Comment by kalxas** [comment]
I am not sure how to replace https://github.com/OSGeo/OSGeoLive/raw/master/app-conf/zoo-project/main.cfg since this is not included in the examples git repo

**Comment by gfenoy** [comment]
> @gfenoy can you please review?

@kalxas, it looks good.

I am wondering if it would not be possible to also introduce the OGC API - Processes demonstration? Indeed, from the [index.html](https://github.com/ZOO-Project/examples/blob/main/index.html#L101) page there is a link to the OAPIP landing page but, I don't see any reference to deploying the configuration file required by this support ([oas.cfg](https://github.com/ZOO-Project/ZOO-Project/blob/main/docker/oas.cfg)) nor downloading swagger-ui.

In case there is no OGC API - Processes activated then, we should probably comment the block containing the link to the OGC API - Processes landing page.

**Comment by kalxas** [comment]
I must be missing something in the OGC API configuration because it is not working for me

**Comment by kalxas** [comment]
The openapi files are installed as part of the zoo-service-openapi debian package

image

**Comment by gfenoy** [comment]
> I must be missing something in the OGC API configuration because it is not working for me

Indeed, from what I can see the files listed [here](https://github.com/ZOO-Project/ZOO-Project/blob/main/docker-compose.yml) from line 17 to 19 are missing. 

Also, I guess that the system would require to have both websocketd and redis installed to get the OGC API - Processes fully functional. You may have a look at the docker-compose.yml file for reference.

**Comment by kalxas** [comment]
The debian package has the following dependencies:

```
Package: zoo-service-openapi
Architecture: any
Depends: python3,
         python3-websockets,
         python3-cheetah,
         redis,
         python3-hiredis,
         python3-appdirs,
         python3-aioredis,
         ${shlibs:Depends},
         ${misc:Depends}
```

**Comment by kalxas** [comment]
ok, thank you, I will review

**Pull request closed without merging**
