### PR TITLE
Add required files for default services

### LINKED ISSUE #18: `/usr/com/zoo-project/` does not contain `topofr.tif` after a default install
**Expected behavior and actual behavior**
The GDAL profile service does not work after a default install

**To Reproduce**

`docker compose up`

**Operating System**
Ubuntu 20.04 64 bit

**ZOO-Project version**
latest

### PR DESCRIPTION
**Pull request by mmomtchev**
Fix #18

### CODE REVIEW

**Comment by mmomtchev** [comment]
@gfenoy or maybe, as an alternative, use the one provided with the default binary image in `/var/www/html/data`?

**Comment by gfenoy** [comment]
> @gfenoy or maybe, as an alternative, use the one provided with the default binary image in `/var/www/html/data`?

Indeed, the [examples repository](https://github.com/ZOO-Project/examples) already contains the required files. But, as we are now using a volume for `/usr/com/zoo-project` the file are only available in `/var/www/html/data` even if they are copied in the right location in the [Dockerfile](https://github.com/ZOO-Project/ZOO-Project/blob/main/Dockerfile#L336) on line 336.

I am wondering if it would be better to use symbolic links from `/usr/com/zoo-project` to `/var/www/html/data` for both `topofr.tif` and `station1.gml`. This way we don't need to download twice the same files.

**Comment by mmomtchev** [comment]
git + symlinks + Windows is a horrible mix
I don't know how is the binary image generated? Or maybe simply configure the GDAL service to use `/var/www/html/data`

**Comment by mmomtchev** [comment]
@gfenoy I think that the best solution is to make Docker prepoluate this directory:
https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container

Where does this file come from? It is not in the git repository, yet it is in the official image?

**Comment by gfenoy** [comment]
> git + symlinks + Windows is a horrible mix

Agreed.

> I don't know how is the binary image generated? Or maybe simply configure the GDAL service to use `/var/www/html/data`

The binary image is generated using a dedicated [GitHub Action](https://github.com/ZOO-Project/ZOO-Project/blob/main/.github/workflows/docker-image.yml).

**Comment by gfenoy** [comment]
> @gfenoy I think that the best solution is to make Docker prepoluate this directory: https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container
> 
> Where does this file come from? It is not in the git repository, yet it is in the official image?

The files required by the examples are stored in another dedicated GitHub repository: https://github.com/ZOO-Project/examples 

This repo is cloned from the Dockerfile used by the GitHub Action: https://github.com/ZOO-Project/ZOO-Project/blob/main/.github/workflows/docker-image.yml responsible for building and pushing the official image

**Comment by mmomtchev** [comment]
Superseded by https://github.com/ZOO-Project/ZOO-Project/pull/25

**Pull request closed without merging**
